tasks:
  - name: setup web
    init: >
      pnpm install &&
      cd server &&
      sh update.sh &&
      cd custom-ts &&
      pnpm install &&
      gp sync-done bundle
    command: pnpm run dev
  - name: setup middleware
    init: gp sync-await bundle
    command: cd server/custom-ts && pnpm run dev
  - name: setup server
    init: gp sync-await bundle
    command: cd server && ./fireboom dev
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9123
    onOpen: open-preview
  - port: 9991
    onOpen: ignore
  - port: 9992
    onOpen: ignore
